library(dplyr)
test_subject <- read.table("./data/UCI HAR Dataset/test/subject_test.txt")
y_test <- read.table("./data/UCI HAR Dataset/test/y_test.txt")
x_test <- read.table("./data/UCI HAR Dataset/test/x_test.txt")
activity_labels <- read.table("./data/UCI HAR Dataset/activity_labels.txt")
train_subject <- read.table("./data/UCI HAR Dataset/train/subject_train.txt")
y_train <-  read.table("./data/UCI HAR Dataset/train/y_train.txt")
x_train <- read.table("./data/UCI HAR Dataset/train/x_train.txt")
features <- read.table("./data/UCI HAR Dataset/features.txt")
labels_test <- merge(activity_labels, y_test, by = "V1")
labels_train <- merge(activity_labels, y_train, by = "V1")
train_set <- cbind(train_subject, labels_train)
test_set <- cbind(test_subject, labels_test)
colnames(train_set) <- c("subject", "label", "activity")
colnames(test_set) <- c("subject", "label", "activity")
train_set <- mutate(train_set, group = "training")
test_set <- mutate(test_set, group = "test")
train_set <- select(train_set, -label)
test_set <- select(test_set, -label)
test_set <- cbind(test_set, x_test)
train_set <- cbind(train_set, x_train)
total_set <- rbind(test_set, train_set)
features_select <- grep("mean|std", features$V2)
colnames(total_set) <- sub("V", "", colnames(total_set))
total_set <- select(total_set, subject:group, all_of(features_select))
new_names <- features[features_select,]
new_names <- new_names$V2
new_names <- c("subject", "activity", "group", new_names)
colnames(total_set) <- new_names
